---
apiVersion: v1
kind: Secret
metadata:
  namespace: docs
  name: sitesearch-pull-secret
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ .Values.Installation.V1.Secret.Registry.PullSecret.DockerConfigJSON | b64enc | quote }}
