apiVersion: apps/v1
kind: Deployment

metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.image.namespace }}
    component: {{ .Values.image.names }}

spec:
  # We want only one ElasticSearch node here.
  # Simplicity over resilience in this case.
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.image.namespace }}
      component: {{ .Values.image.name }}
  template:
    metadata:
      name: {{ .Values.name }}
      labels:
        app: {{ .Values.image.namespace }}
        component: {{ .Values.image.name }}
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: {{ .Values.image.name }}
          image: quay.io/giantswarm/{{ .Values.image.name }}:{{ .Values.image.sha }}
          ports:
            - containerPort: 9200
              name: http
          resources:
            requests:
              cpu: 200m
              memory: 700M
            limits:
              cpu: 500m
              memory: 700M
          volumeMounts:
            - name: logs-volume
              mountPath: /logs
            - name: data-volume
              mountPath: /data
      volumes:
        - name: logs-volume
          emptyDir: {}
        - name: data-volume
          emptyDir: {}
      imagePullSecrets:
        - name: {{ .Values.image.name }}-pull-secret
      serviceAccount: {{ .Values.name }}
      serviceAccountName: {{ .Values.name }}
