kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: managed-standard
