kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Namespace }}-{{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: gp3
