kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  ports:
    - port: 9200
      targetPort: http
  selector:
    app: {{ .Values.name }}
