kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.image.name }}
  labels:
    app: {{ .Values.namespace }}
    component: {{ .Values.name }}
spec:
  ports:
    - port: 9200
      targetPort: http
  selector:
    app: {{ .Values.image.namespace }}
    component: {{ .Values.image.names }}
